### ISSUE TITLE
Need LICENSE file

### ISSUE THREAD

**Issue by masinter** [Interlisp/maiko#1]
we should say copyright (c) 2009 Venue

Where 2009 is the last year there were any Venue edits.
and then include the MIT License

**Comment by nbriggs** [comment]
Yes, but to whom does the copyright for changes subsequent to 2009 belong (e.g., all the bug fixes so far)?

One of the projects (VLC) that I follow uses "Copyright (C) 2020 VLC Authors and VideoLAN" where they actually have an organization that has done a lot of work and open sources it, but any random person who contributes is a "VLC Author".

-- Nick
