### ISSUE TITLE
GETBITS opcode 312 returns negative numbers 

### ISSUE THREAD

**Issue by masinter** [Interlisp/maiko#4]
if you PRINTCODE(PRINTCODENT) it will show large negative numbers for the FVAR table.

I think it might be the same problem of signed characters in GETBASEBYTE

#define GETBITS_N_M(a, b)						\
		{register int temp, bb = b;					\
		temp = 0xF & bb;						\
		TOPOFSTACK = S_POSITIVE | 				\
		 (( (GETWORD(Addr68k_from_LADDR(POINTERMASK & (TOPOFSTACK+a))))	\
			>> (16 - ( (0xF & (bb >> 4)) + temp + 1)) )	\
			& n_mask_array[temp] );				\
		 nextop3;						\
		}

**Comment by nbriggs** [comment]
![Screen Shot 2020-08-08 at 12 38 42 PM](https://user-images.githubusercontent.com/8138841/89718531-22b5e080-d974-11ea-8210-ef54823ff3c6.png)
I see the problem in the output, but I don't think that it is the code implementing GETBITS_N_M that can be causing this.
That code expands to
```
    case 0312:
    ; case312:
      {register int temp, bb = (((BYTECODE *)((char *) (3^(unsigned long)((pccache - 1)+2))))->code);
       temp = 0xF & bb;
       tscache = 0xE0000 |
           (( ((* (DLword *) (2^(unsigned long)((Lisp_world + (0xfffffff & (tscache+(((BYTECODE *)((char *) (3^(unsigned long)((pccache - 1)+1))))->code)))))))) >>
              (16 - ( (0xF & (bb >> 4)) + temp + 1)))
            & n_mask_array[temp] );
        {pccache += 3;
         {goto nextopcode; }; }; };
```
and so the top-of-stack will always be less than n_mask_array[15], which is 0xFFFF (from a 32-bit signed int array)

**Comment by masinter** [comment]
I just figured that out. I'm a little hampered because I havent set up to  use whereis.hash to find the printcode source

**Comment by nbriggs** [comment]
I use grep on the lispcore/sources to find Lisp code -- for example
```
% grep -l PRINTCODE * | grep -v '~'
grep: CLTL2: Is a directory
grep: obsolete: Is a directory
ACODE
ACODE.LCOM
CMLCOMPILE
CMLCOMPILE.LCOM
DPUPFTP
DPUPFTP.LCOM
INSPECT
INSPECT.LCOM
LLINTERP
system.hash
```
and then look at the files using a text editor.  To deal with the CR/LF issue, sometimes I'll do, for example
```
% tr '\015' '\012' < ACODE >/tmp/acode
```

**Comment by masinter** [comment]
I got it down to

(LLSH 8388808 8) => -2147322448

**Comment by nbriggs** [comment]
Looking in shift.c, I find I've been here before and noted:

/*                                                                                                                                                                                        
 * XXX: it feels as though something is not clean here, looks like the                                                                                                                    
 * "int a" arguments are really LispPTR types, though perhaps it doesn't                                                                                                                  
 * matter.  NBriggs, May 2017                                                                                                                                                             
 */

**Comment by masinter** [comment]
i'm looking at N_ARITH_SWITCH in arith.h

**Comment by nbriggs** [comment]
It's executing this code, I think, from LLARITH:
```
(llsh
  (lambda (x n)                                              (* |lmm| "13-OCT-82 15:30")
    (cond
       ((igreaterp 0 n)
        (lrsh x (iminus n)))
       (t (prog (xhi xlo)
                (.unbox. x xhi xlo)
                (cond
                   ((igreaterp n 31)
                    (return 0)))
                (cond
                   ((igreaterp n 15)
                    (setq xhi xlo)
                    (setq xlo 0)
                    (setq n (idifference n 16))))
                (cond
                   ((igreaterp n 7)
                    (setq xhi (iplus (llsh (logand xhi 255)
                                           8)
                                     (lrsh xlo 8)))
                    (setq xlo (llsh (logand xlo 255)
                                    8))
                    (setq n (idifference n 8))))
                (frptq n (setq xhi (logand xhi max.pos.hinum))
                       (.llsh1. xhi xlo))
                (return (\\makenumber xhi xlo)))))))

```

**Comment by nbriggs** [comment]
But, if it does make it down to actually execute an LLSH8 opcode,  N_ARITH_SWITCH always stuffs the result into a FIXP, so I'm unclear on whether the result you saw is not the result one should expect...?

**Comment by masinter** [comment]
i'm sorry for the false alarm. LLSH is doing the "right" thing for Interlisp, just wrong for common lisp (which would convert to bignum). I don't remember why there was a LLSH8 and an LLSH1 opcode? 
The chase gave me some experience with the code. I think the bug is in PRINTCODENT -- shouldn't be computing the 4 byte atom number that way

**Comment by nbriggs** [comment]
OK, closed: the emulator is operating as intended.  Not sure if you want to open an issue on PRINTCODENT.
